### ISSUE TITLE
Does it support the Chinese input?

### ISSUE THREAD

**Issue by bluesummerbreeze** [rainmanwy/robotframework-SikuliLibrary#1]
I want to type Chinese characters, but it seems doesn't support. I saw paste(u"中文") can be ok in sikuliapi. Then how to input  Chinese characters?

**Comment by rainmanwy** [comment]
Hi,

After dig this problem. I found this answer from sikuli author.
https://answers.launchpad.net/sikuli/+question/230048

i have added a keyword named "Paste Text", it looks ok for non-english.
If you could build the package yourself. you could clone the latest version and have a try.

I will upload to pypi later when there are more modified.

Thank you very much!

**Comment by bluesummerbreeze** [comment]
Bravo! Thanks so much for your help.

**Comment by bluesummerbreeze** [comment]
Hi,I tried to build the package,but there's something wrong with it. I'm new to python,so,can you tell me how to build the package? Maybe  you can upload your setup.py.
 
Thanks very much!

**Comment by rainmanwy** [comment]
Actually keyword part is implemented with java. You have to install maven to build it.
command: mvn package 

If you are behind of proxy. May need configure proxy for maven.
https://maven.apache.org/install.html

Do you have any experience about maven. If you could not build yourself. I could create windows and linux version for you. But the file size is a little big.

**Comment by rainmanwy** [comment]
I have uploaded to latest version to pypi. You may have a try.
https://pypi.python.org/pypi/robotframework-SikuliLibrary

**Comment by bluesummerbreeze** [comment]
Nice going! ;)

**Comment by bluesummerbreeze** [comment]
$ mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building robotframework-SikuliLibrary 1.0
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/groups/public/jxgrabkey/jxgrabkey/
1.0/jxgrabkey-1.0.pom
Downloading: https://labs.consol.de/maven/repository/jxgrabkey/jxgrabkey/1.0/jxg
rabkey-1.0.pom
Downloading: http://mvn.is.inf.uni-due.de:8081/nexus/content/repositories/atunes
-dependencies/jxgrabkey/jxgrabkey/1.0/jxgrabkey-1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.557 s
[INFO] Finished at: 2016-04-07T16:23:55+08:00
[INFO] Final Memory: 12M/108M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project robotframework-SikuliLibrary: Could no
t resolve dependencies for project com.github.rainmanwy.robotframework:robotfram
ework-SikuliLibrary:jar:1.0: Failed to collect dependencies at com.sikulix:sikul
ixapi:jar:1.1.0 -> jxgrabkey:jxgrabkey:jar:1.0: Failed to read artifact descript
or for jxgrabkey:jxgrabkey:jar:1.0: Could not transfer artifact jxgrabkey:jxgrab
key:pom:1.0 from/to jxgrabkey (https://labs.consol.de/maven/repository/): Receiv
ed fatal alert: handshake_failure -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

Do you know how to resolve it?

**Comment by rainmanwy** [comment]
So, you built it on linux?
Which java version are you using? I am not sure whether it is related with java security problem.

maybe you could replace 
<url>https://labs.consol.de/maven/repository/</url>
with 
<url>http://mvn.is.inf.uni-due.de:8081/nexus/content/repositories/atunes-dependencies/</url>


if it is ok, i may modify pom in repo.

**Comment by bluesummerbreeze** [comment]
no,I'm using jdk1.7 & building on windows...=。=
http://mvn.is.inf.uni-due.de:8081/nexus/content/repositories/atunes-dependencies/, I replaced,but it didn't work.

**Comment by rainmanwy** [comment]
$ mvn package
i found "$" here. So you build it in cygwin?

**Comment by rainmanwy** [comment]
when using new url, what happened?

**Comment by bluesummerbreeze** [comment]
no,I execute command with git bash,so there is a "$".

Here is new log:
$ mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building robotframework-SikuliLibrary 1.0
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/groups/public/jxgrabkey/jxgrabkey/
1.0/jxgrabkey-1.0.pom
Downloading: http://mvn.is.inf.uni-due.de:8081/nexus/content/repositories/atunes
-dependencies/jxgrabkey/jxgrabkey/1.0/jxgrabkey-1.0.pom
Downloading: http://mvn.is.inf.uni-due.de:8081/nexus/content/repositories/atunes
-dependencies/jxgrabkey/jxgrabkey/1.0/jxgrabkey-1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:10 min
[INFO] Finished at: 2016-04-07T17:18:07+08:00
[INFO] Final Memory: 11M/80M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project robotframework-SikuliLibrary: Could no
t resolve dependencies for project com.github.rainmanwy.robotframework:robotfram
ework-SikuliLibrary:jar:1.0: Failed to collect dependencies at com.sikulix:sikul
ixapi:jar:1.1.0 -> jxgrabkey:jxgrabkey:jar:1.0: Failed to read artifact descript
or for jxgrabkey:jxgrabkey:jar:1.0: Could not transfer artifact jxgrabkey:jxgrab
key:pom:1.0 from/to jxgrabkey (http://mvn.is.inf.uni-due.de:8081/nexus/content/r
epositories/atunes-dependencies/): Connect to mvn.is.inf.uni-due.de:8081 [mvn.is
.inf.uni-due.de/134.91.35.230] failed: Connection timed out: connect -> [Help 1]

[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by rainmanwy** [comment]
could you access http://mvn.is.inf.uni-due.de:8081/nexus/content/repositories/atunes-dependencies/ with your browser?

Whether you are behind of proxy, whether 8081 is blocked by firewall?
And you may package it in windows cmd.

and have you tried the install package in pypi?

**Comment by bluesummerbreeze** [comment]
能给个微信号或者其他即时通讯方式么=。=

**Comment by rainmanwy** [comment]
Rainmanwy微信
