### ISSUE TITLE
Getting error No keywords found

### ISSUE THREAD

**Issue by Prashant3100** [rainmanwy/robotframework-SikuliLibrary#10]
While using the SikuliLibrary in Robot framework test, getting error No keywords found.

**Comment by rainmanwy** [comment]
What the OS you are using? And how do you install this library?

You may check whether this answer could help you.
https://answers.launchpad.net/sikuli/+question/295568

**Comment by Prashant3100** [comment]
HI Wang, 
Appreciate your time and prompt response, I am on Mac and Using Robot framework and i am running my script by 'pybot my_test.robot'  command. 
Could you please guide me to process or any missing package required to run it on MAC.?
Thanks. 
Here is the Error I am getting, 
[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:65271/ failed: [Errno 61] Connection refused[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:65271/ failed: [Errno 61] Connection refused[ ERROR ] Error in file '/Users/username/PycharmProjects/h5/resource/keywords_SikuliTest.robot': Initializing test library 'SikuliLibrary' with no arguments failed: Failed to get_keyword_names!Traceback (most recent call last):  File "/usr/local/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 41, in __init__    self.remote = self._connect_remote_library()  File "/usr/local/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 138, in _connect_remote_library    self._test_get_keyword_names(remote)  File "/usr/local/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 155, in _test_get_keyword_names    raise RuntimeError('Failed to get_keyword_names!')

 Regards,Prashant Bharambe When the world says, "Give up,"
  Hope whispers, "Try it one more time"

 

    On Monday, 22 August 2016 5:56 PM, Rainmanwy <notifications@github.com> wrote:
 

 What the OS you are using? And how do you install this library?You may check whether this answer could help you.
https://answers.launchpad.net/sikuli/+question/295568—

**Comment by rainmanwy** [comment]
1. start server.
rainman@ubuntu:~/workspace/GitHub/robotframework-SikuliLibrary/target/src/SikuliLibrary/lib$ java -jar SikuliLibrary.jar 10000 .

2. Use remote library to connect server and get keyword list.
rainman@ubuntu:~$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:38)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from robot.libraries.Remote import Remote
>>> remote = Remote('http://127.0.0.1:10000/')
>>> remote.get_keyword_names()

3. Check output of server, whether there are some error info.

and you may check this doc.
http://www.sikulix.com/quickstart/


btw, how do you installed this library, through pip, or source installation. I suggest you to install it through source, using maven.
command like:
mvn package
python setup.py install

**Comment by Prashant3100** [comment]
HI Again, 
Thanks for replying 
Yes, Now 1st Part works fine as below 
 -jar SikuliLibrary.jar 100000 [main] INFO org.robotframework.remoteserver.RemoteServer  - Mapped path / to library com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.1 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server starting1 [main] INFO org.eclipse.jetty.server.Server  - jetty-7.x.y-SNAPSHOT21 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - started o.e.j.s.ServletContextHandler{/,null}77 [main] INFO org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:1000078 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server started on port 10000.
But 2nd part I am not sure if i am doing right     - Installed the Remote Library
    - Set it up in my script as 
        - Library  Remote  http://127.0.0.1:10000

While running my script getting this error,[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:50741/ failed: [Errno 61] Connection refused[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:50741/ failed: [Errno 61] Connection refused[ ERROR ] Error in file '/Users/username/PycharmProjects/h5/resource/keywords_SikuliTest.robot': Initializing test library 'SikuliLibrary' with no arguments failed: Failed to get_keyword_names!Traceback (most recent call last):  File "/usr/local/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 41, in __init__    self.remote = self._connect_remote_library()  File "/usr/local/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 138, in _connect_remote_library    self._test_get_keyword_names(remote)  File "/usr/local/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 155, in _test_get_keyword_names    raise RuntimeError('Failed to get_keyword_names!')[ ERROR ] Error in file '/Users/username/PycharmProjects/h5/resource/keywords_SikuliTest.robot: Getting keyword names from library 'Remote' failed: Calling dynamic method 'get_keyword_names' failed: Connecting remote server at http://127.0.0.1:10000 failed: <ProtocolError for 127.0.0.1:10000/RPC2: 404 No library mapped to /RPC2>
Could you please suggest what i am doing wrong. 
thanks in advance. 
 

    On Monday, 22 August 2016 9:25 PM, Rainmanwy <notifications@github.com> wrote:
 

    
   - start server.   
rainman@ubuntu:~/workspace/GitHub/robotframework-SikuliLibrary/target/src/SikuliLibrary/lib$ java -jar SikuliLibrary.jar 10000 .
   - Use remote library to connect server and get keyword list.   
rainman@ubuntu:~$ python   
Python 2.7.6 (default, Mar 22 2014, 22:59:38)   
[GCC 4.8.2] on linux2   
Type "help", "copyright", "credits" or "license" for more information.   
   
   
from robot.libraries.Remote import Remote   
remote = Remote('http://127.0.0.1:10000/')   
remote.get_keyword_names()



   - Check output of server, whether there are some error info.
and you may check this doc.
http://www.sikulix.com/quickstart/btw, how do you installed this library, through pip, or source installation. I suggest you to install it through source, using maven.
command like:
mvn package
python setup.py install—

**Comment by rainmanwy** [comment]
there is '/' at end of "http://127.0.0.1:10000/". I remember that no "/" may meet problem.

Could you check your robot version? using "pybot --version"

**Comment by Prashant3100** [comment]
Thanks, 
I don't know from where '/' is coming at the end. 
and I am using /Robot Framework 3.0 (Python 2.7.9 on darwin)''
 Regards,Prashant Bharambe When the world says, "Give up,"
  Hope whispers, "Try it one more time"

 

    On Tuesday, 23 August 2016 1:39 AM, Rainmanwy <notifications@github.com> wrote:
 

 there is '/' at end of "http://127.0.0.1:10000/". I remember that no "/" may meet problem.Could you check your robot version? using "pybot --version"—

**Comment by Prashant3100** [comment]
Hi Wang, 
Got more details, 
0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Mapped path / to library com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.
1 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server starting
1 [main] INFO org.eclipse.jetty.server.Server  - jetty-7.x.y-SNAPSHOT
22 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - started o.e.j.s.ServletContextHandler{/,null}
80 [main] INFO org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:54125
80 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server started on port 54125.
*** classpath dump 
  0: /usr/local/lib/python2.7/site-packages/SikuliLibrary/lib/SikuliLibrary.jar
*** classpath dump end
[error] RunTimeINIT:  *** terminating: libs to export not found on above classpath: /sikulixlibs/mac/libs64
I see there is no mac/libs64 directory in sikulixlibs. 
Please suggest.   Regards,Prashant Bharambe When the world says, "Give up,"
  Hope whispers, "Try it one more time"

 

    On Tuesday, 23 August 2016 8:53 AM, prashant bharambe <prashant_bharambe143@yahoo.com> wrote:
 

 Thanks, 
I don't know from where '/' is coming at the end. 
and I am using /Robot Framework 3.0 (Python 2.7.9 on darwin)''
 Regards,Prashant Bharambe When the world says, "Give up,"
  Hope whispers, "Try it one more time"

 

    On Tuesday, 23 August 2016 1:39 AM, Rainmanwy <notifications@github.com> wrote:
 

 there is '/' at end of "http://127.0.0.1:10000/". I remember that no "/" may meet problem.Could you check your robot version? using "pybot --version"—

**Comment by rainmanwy** [comment]
Hi,

You'd better compile and package this library yourself. 
In pypi, i just uploaded windows and linux version.

for source installation, you need install maven and execute below command:
mvn package
python setup.py install

**Comment by Prashant3100** [comment]
Thank a lot, 
I already did this rebuild the package and replace the SikuliLibrary.jar file. 
Now its fetching the keywords. 
Further I have to figure out the multiple keywords problem like 'Input Text' all the three Library (Selenium2Library, SikuliLibrary, Remote) I am using has same keywords.  Thanks Wang for your time and replying promptly on my issue. 
 Regards,Prashant Bharambe When the world says, "Give up,"
  Hope whispers, "Try it one more time"

 

    On Tuesday, 23 August 2016 5:45 PM, Rainmanwy <notifications@github.com> wrote:
 

 Hi,You'd better compile and package this library yourself. 
In pypi, i just uploaded windows and linux version.for source installation, you need install maven and execute below command:
mvn package
python setup.py install—

**Comment by rainmanwy** [comment]
Ok.

About keyword conflicts, could add library name when call it in robot case, for example "SikuliLibrary.Input Text".

**Comment by Prashant3100** [comment]
Thanks..doing same. Regards,Prashant Bharambe When the world says, "Give up,"
  Hope whispers, "Try it one more time"

 

    On Wednesday, 24 August 2016 5:36 PM, Rainmanwy <notifications@github.com> wrote:
 

 Ok.About keyword conflicts, could add library name when call it in robot case, for example "SikuliLibrary.Input Text".—
