### ISSUE TITLE
java.lang.NoSuchMethodError: com.sun.jna.Native.load

### ISSUE THREAD

**Issue by crbreingan** [rainmanwy/robotframework-SikuliLibrary#105]
I'm running with JDK 8.0.2020.8 (Java 8 update 202, 64-bit), Python 3.6.1 :: Anaconda 4.4.0 (64-bit)

I'm trying a basic Click operation, but it fails with "java.lang.NoSuchMethodError: com.sun.jna.Native.load". It appears to be an issue with the JNA versions. What version was used to compile the SikuliLibrary.jar file?

**Comment by rainmanwy** [comment]
@crbreingan , which SikuliLibrary version is installed in your env?
[sikulilibrary version](https://pypi.org/project/robotframework-SikuliLibrary/#history)

Could you have a try version 1.0.5

I am using JDK 8 to compile and package.

**Comment by RaiMan** [comment]
RaiMan from SikuliX:
Sorry for the inconvenience: If it is 1.1.4: Please recompile/pack with the latest snapshot from yesterday.

**Comment by rainmanwy** [comment]
@RaiMan , so "sikulixapi-1.1.4-20190618.120945-196.jar" have fixed this issue, right? And is it only related with Windows. As my env is Linux, and i haven't found this error.

**Comment by RaiMan** [comment]
yes, Windows specific. Better support for non-us keyboards and other gimmiks

**Comment by rainmanwy** [comment]
@crbreingan , i haven't windows env and could not test it, you may upgrade the version to 1.0.7 and tell me whether it is ok.
@RaiMan , thank you very much:)
