### ISSUE TITLE
Paste Text keyword may determine "Paste text failed" with package ScreenKeywords line 399

### ISSUE THREAD

**Issue by ClaudeJian** [rainmanwy/robotframework-SikuliLibrary#106]
Hi,
I used robotframework-SikuliLibrary version 1.0.7.
The text content is pasted successful but always return "**com.github.rainmanwy.robotframework.sikulilib.exceptions.ScreenOperationException: Paste text failed**"
I think that is related the line 399 of package com.github.rainmanwy.robotframework.sikulilib.keywords
[https://github.com/rainmanwy/robotframework-SikuliLibrary/blob/master/src/java/com/github/rainmanwy/robotframework/sikulilib/keywords/ScreenKeywords.java](url)

If I'm right,the result is checking whether the text content is read successful.

I also check similar keyword "Input Text" that check the result == 0 then output the error message.

![image](https://user-images.githubusercontent.com/34434055/59835247-e7291300-937b-11e9-8664-829a2ae14fe5.png)

**Comment by rainmanwy** [comment]
@ClaudeJian , the return value of "paste" has changed, thank you very much! I have uploaded the fix version to pypi, you may have a try!

**Comment by ClaudeJian** [comment]
Hi,
Thanks for kindly reply and effective fix.
I had verified it with 1.0.8, that is working properly.

**Comment by alfeducor3** [comment]
Hi @rainmanwy sorry if I should open a new issue, I was not sure if adding a comment to this closed one was the right approach, but I am getting same exact error using robotframework-SikuliLibrary 2.0.0. Do I need to use a previous version for using Paste Text ?

![image](https://user-images.githubusercontent.com/74790919/102789118-8b688d00-4358-11eb-8dec-278daf5006ca.png)

**Comment by pravinalhat-zymr** [comment]
@alfeducor3 Please use Run Keyword And Ignore Error before Paste Text keyword like
Run Keyword And Ignore Error    Paste Text    abc.png    Hello

 I hope this will help you to get rid of this exception.
