### ISSUE TITLE
Jenkins - RobotFramework build failed due to connection to Sikuli remote server.

### ISSUE THREAD

**Issue by gamer20052** [rainmanwy/robotframework-SikuliLibrary#109]
Hello,
I am trying to get a Jenkins server to run my local RF script. The library being used is Sikuli. Based on the error, I may need to set the port for IP address 127.0.0.1, which I thought was already defaulted. From the RF Sikuli Library github, I tried starting the Sikuli process manually but it provided the same error. The script itself is successful when ran from the command line.

The Jenkins project itself is very simple and has all required environmental variables to run any shell scripts called. A short snippet of the report from Jenkins is shown below.

robot test5.robot
[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:51505/ failed: <Fault 0: 'Failed to invoke method get_keyword_names in class org.robotframework.remoteserver.servlet.ServerMethods: java.lang.RuntimeException'>
[ ERROR ] Error in file '/home/ale/robot/test5.robot': Initializing test library 'SikuliLibrary' with no arguments failed: Failed to get_keyword_names!
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 54, in init
self.start_sikuli_process(port)
File "/usr/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 93, in start_sikuli_process
self.remote = self._connect_remote_library()
File "/usr/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 208, in _connect_remote_library
self._test_get_keyword_names(remote)
File "/usr/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 225, in _test_get_keyword_names
raise RuntimeError('Failed to get_keyword_names!')

**Comment by rainmanwy** [comment]
Could you confirm that SikuliLibrary could work on the machine which installed jenkins. 
You could check doc of sikulix, that there are some extra requirements for linux environment.
And another requirement is sikulix works in desktop environment, for linux, may need config DISPLAY environment variable before running sikuli

**Comment by gamer20052** [comment]
Everything works fine when I run on the command line "robot test5.robot". However, it is when I run the robot script via Jenkins that I experience the issue.
I am using Jenkins on the same Linux desktop to drive my robot framework script. I believe there may be some weird interaction happening between Jenkins and the Sikuli Library when it is called. I don't understand how the port can be recognized when ran from the command line but not when ran on the Jenkins "command line" like script.

**Comment by rainmanwy** [comment]
@gamer20052 , you may check below link about "DISPLAY" environment variable
[DISPLAY](https://askubuntu.com/questions/432255/what-is-the-display-environment-variable)

if jenkins is running background, and the job is not configured with DESKTOP, it may meet problems when job is related with DESKTOP, for example, "Open Browser" in job. And Sikulix need DESKTOP Environment, so this library may meet problem when executed background.

**Comment by gamer20052** [comment]
Thank you Rainmanwy but I had DESKTOP configured. Further investigations have found that the permissions to the SikuliLIbrary were set to only my username. No matter how we changed permissions to the robot directory or the library, only my username account could call from the remote server (Referencing to https://github.com/rainmanwy/robotframework-SikuliLibrary/issues/10). Root and another other directories were not capable. Going to just install everything again as root and redo. Thanks for your suggestions and time!
