### ISSUE TITLE
java process in not closing after script execution.

### ISSUE THREAD

**Issue by Raghu6519** [rainmanwy/robotframework-SikuliLibrary#12]
Hi,

I'm using robotframework 3.0. installed Sikuli library from source using maven. When i run a script SikuliLibrary.jar is started, even after script execution is completed the java process is still running. next time when i run the script again a new process is created. i'm facing this issue in both Linux(RHEL) and Windows. 

i will be running multiple scripts repeatedly and because of this issue RAM is getting filled with java process.
here is the java process from linux server

root     21509     1  0 08:59 pts/26   00:00:16 java -jar /usr/jython/Lib/site-packages/SikuliLibrary/lib/SikuliLibrary.jar 55994 /tmp/xtttrrr
root     21769     1  0 11:27 pts/32   00:00:17 java -jar /usr/jython/Lib/site-packages/SikuliLibrary/lib/SikuliLibrary.jar 59637 /tmp/xtttrrr

Regards,
Raghu

**Comment by rainmanwy** [comment]
you could check this wiki
https://github.com/ombre42/jrobotremoteserver/wiki/Getting-Started#Stopping_the_Server
