### ISSUE TITLE
sikuli installation error on redhat 7

### ISSUE THREAD

**Issue by Raghu6519** [rainmanwy/robotframework-SikuliLibrary#121]
Hi,

I'm trying to install sikuli library on redhat 7 server. Using pip installation was successful but when we run robot script it fails with java error. 
`[error] RunTimeAPI: loadLib: opencv_java not usable:
java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path`

Could you please help to resolve this issue.

regards,
Raghavender

**Comment by jpeltonen** [comment]
I think pip installation is only supported for Windows. If you are installing for Linux you should build the from source code using maven.

**Comment by Raghu6519** [comment]
> Seems like opencv library is missing from your system. Could you check if this helps http://www.sikulix.com/specials/files/linux-setup-prerequisites.html

Thank you, We found few dependencies for ubuntu, trying to find similar packages for redhat and install them.
meanwhile we are trying to build the library from source using "mvn package" command. we see following error message:

[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks

main:
     [echo] unzip package
    [unzip] Expanding: /home/pgoud/robotframework-SikuliLibrary/target/SikuliLibrary.zip into /home/pgoud/robotframework-SikuliLibrary/target/src
     [echo] generate keywords.py
     [exec] /usr/bin/python: No module named robot.libraries.Process
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:12.994s
[INFO] Finished at: Mon Feb 17 03:00:14 MST 2020
[INFO] Final Memory: 79M/289M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (dist) on project robotframework-SikuliLibrary: An Ant BuildException has occured: exec returned: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Could you please let us know what we are missing here?

**Comment by Raghu6519** [comment]
Hi, 

Figured that maven was looking for "robot.libraries.Process" in python2 path, but I was trying to install library to python3. Installing robot to python2 resolved issue. Also "ant" was missing so installed it. 
Next step was to build OpenCV from source and create symlink for libopecv_java.so. That solved our issue.

Thanks.
