### ISSUE TITLE
Bug in Right Click In

### ISSUE THREAD

**Issue by jpeltonen** [rainmanwy/robotframework-SikuliLibrary#13]
198     @RobotKeyword("Right click in. \nRight click target image in area image.") 
199     @ArgumentNames({"areaImage", "targetImage"}) 
200     public void rightClickIn(String areaImage, String targetImage) throws Exception { 
201         Match match = wait(areaImage, Double.toString(this.timeout)); 
202         System.out.println(areaImage + " is found!"); 
203         match.rightClick(targetImage); 
204         capture(match.find(targetImage)); 
205     } 

If there is a context menu opening then line 204 capture(match.find(targetImage));  might fail, because it might overlap with targetImage. 

To fix this Line 204 should be before line 203:
204         capture(match.find(targetImage)); 
203         match.rightClick(targetImage);

**Comment by jpeltonen** [comment]
This also affects doubleClickIn() and clickIn(), because targetImage might change on screen after clicking it.

**Comment by rainmanwy** [comment]
thanks @jpeltonen .

[78ddb57 ](url)

**Comment by jpeltonen** [comment]
Thank you for Sikuli Robot Framework Library :) It find it very usefull.

**Comment by rainmanwy** [comment]
Nothing! Actually i haven't rich sikuli experiences, and not used it in my daily work. If you have any other suggestions or pull requests, no hesitate to tell me. Thanks!
