### ISSUE TITLE
_wait_process_started() raises exception sometimes in sikuli.py

### ISSUE THREAD

**Issue by jpeltonen** [rainmanwy/robotframework-SikuliLibrary#14]
Raises 'Start sikuli java process failed!' sometimes when starting sikuli java process in Windows Server 2008 R2 environment. Don't know the reason (maybe related to getting free tcp port?) but retrying  _start_sikuli_java_process() in case of exception seems to help like in the code below:

def **init**(self, port=0, timeout=20.0, mode=''):
        """
        @port: sikuli java process socket port
        @timeout: Timeout of waiting java process started
        @mode: if set as 'DOC',  will stop java process automatically, 
               if set as 'PYTHON', means library is running in out of robot environment
        """
        self.logger = self._init_logger()
        self.timeout = float(timeout)
        if int(port) == 0:
            port = self._get_free_tcp_port()
        self.port = port
        start_retries = 0
        started = False
        while(start_retries < 5):
            try:
                self._start_sikuli_java_process()
            except RuntimeError, err:
                if(self.process):
                    self.process.terminate_process()
                self.port = self._get_free_tcp_port()
                start_retries += 1
                continue
            started = True
            break
        if not started:
            raise RuntimeError('Start sikuli java process failed!')

```
    self.remote = self._connect_remote_library()
    if mode.upper().strip() == 'DOC':
        self._stop_thread(4)
    elif mode.upper().strip() == 'PYTHON':
        pass
    else:
        self._check_robot_running()
```

**Comment by rainmanwy** [comment]
Have you checked Sikuli_java_stdout_<timestamp>.txt and Sikuli_java_stderr_<timestamp>.txt whether there are some information? _wait_process_started() will check whether the web page of java process could be accessed. The default timeout value is 20s, maybe you could change it to longer and check whether it is help. If it is really tcp port problem, then your solution could be used.

**Comment by jpeltonen** [comment]
Found error something in log that could be related to issue.

[Sikuli_java_stdout_1475689240.36.txt](https://github.com/rainmanwy/robotframework-SikuliLibrary/files/535442/Sikuli_java_stdout_1475689240.36.txt)

**Comment by rainmanwy** [comment]
So remote server met problem.

Could you check whether java process is still there when this error happened?
If process is still there, we needed to kill it firstly, then have a try to start a new process to handle this error.

**Comment by jpeltonen** [comment]
Yes I think that the Java process is running there, but I can't communicate with it so I check if the process has pid and then kill it an try again:
if(self.process):
self.process.terminate_process()
