### ISSUE TITLE
TimeoutException: Timeout happend, could not find P(po.png)

### ISSUE THREAD

**Issue by hxr1990** [rainmanwy/robotframework-SikuliLibrary#151]
Jenkins remote call RF script on the server failed but the server runs the RF script directly through

Jenkins error messages：
com.github.rainmanwy.robotframework.sikulilib.exceptions.TimeoutException: Timeout happend, could not find P(po.png) S: 0.699999988079071

**Comment by dschiller** [comment]
`S` here means the Match Score. As I understand maybe the Match Score is `0.69..` you could try to lower the Score to match the `6.9` via:

````
...
  ${imageScore}  Get Match Score  ${image}
  IF ${imageScore} >= 6.9
    Log to Console. Found the Image
  ELSE
    Log to Console. Couldn't find t he Image
  END
...

**Comment by rainmanwy** [comment]
maybe it is because of different screen resolutions.
