### ISSUE TITLE
Click Region and other keywords taking region coordinates as input not working

### ISSUE THREAD

**Issue by sehajsasan** [rainmanwy/robotframework-SikuliLibrary#157]
I just want to click on a region by providing its coordinates but when I write the keyword as 
Click Region  [100,210,30,40]
it throws Check Region                                                          | FAIL |
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.get(int)" because "cooridnates" is null

<img width="874" alt="log" src="https://user-images.githubusercontent.com/50807883/125411680-c527e080-e3db-11eb-86f4-952d33f6104f.PNG">

other keywords are working fine but the ones with coordinates as arguments to act on the coordinates as a region throw the same error/exception. How to use these keywords to just act on a region by providing its coordinates and not use any image matching or finding operation.

**Comment by rainmanwy** [comment]
I have update doc, should be like 
```
${coor}  Create List  0  0  100  100
Click Region   ${coor} 
```
