### ISSUE TITLE
Input Text keyword documentation has wrong example

### ISSUE THREAD

**Issue by lucielavickova-tesena** [rainmanwy/robotframework-SikuliLibrary#160]
In the Input Text keyword documentation, there is written that image attribute could be empty, providing an example:
![image](https://user-images.githubusercontent.com/83921517/131573486-2704a2a4-4de9-4797-bfe8-50c3de60bc59.png)

But when I tried this in my project, the test failed saying `Keyword 'SikuliLibrary.Input Text' expected 2 arguments, got 1.`

After a short investigation I found out, that the image attribute can be empty, but has to be provided. 

So the example should look like this:
`Input Text  ${EMPTY}  text`

Please fix the documentation, thank you

**Comment by rainmanwy** [comment]
thank you lucie
