### ISSUE TITLE
Elements not found by Sikuli when Screen Scaling different from 100%

### ISSUE THREAD

**Issue by lucielavickova-tesena** [rainmanwy/robotframework-SikuliLibrary#162]
I was facing an issue with elements not found by Sikuli lately - none of the screenshots I took was working, until I noticed the screenshots in my IDE preview are slightly bigger than the elements actually displayed on the screen. This was because of my screen scaling settings. I had my screen resolution set to 1920x1080 and scaling (size of text, icons etc.) to 125% as recommended by the operating system. Once I set the scaling to 100% and re-took the screenshots, Sikuli started recognizing elements without problems. 

In the official Sikuli documentation, I read about "Always Resize" settings possibility: https://sikulix-2014.readthedocs.io/en/latest/scripting.html#Settings.AlwaysResize 
Is there something similar in the SikuliLibrary for Robot Framework, too? Or isn't it solving the issue?

Or at least it would be good to make a note about this prerequisity in the docs - to have scaling set to 100% before starting to work with Sikuli.

**Comment by rainmanwy** [comment]
add keyword "setAlwaysResize"
