### ISSUE TITLE
Add expected parameter value to Set Min Similarity keyword documentation

### ISSUE THREAD

**Issue by lucielavickova-tesena** [rainmanwy/robotframework-SikuliLibrary#164]
Please add info about the expected parameter value to the Set Min Similarity keyword documentation (for setting minimal accuracy when searching for elements). 

The documentation says only following:
![image](https://user-images.githubusercontent.com/83921517/132511269-8dcaf516-ab9d-45ae-a33b-afe79c25f561.png)

so I just had to guess what to pass in so that it starts working.
Based on the official sikuli documentation, it **should be a decimal number between 0 and 1**

**Comment by rainmanwy** [comment]
thank you, Lucie
