### ISSUE TITLE
How to click the exactly text while using the Click Text

### ISSUE THREAD

**Issue by JerryXinhui** [rainmanwy/robotframework-SikuliLibrary#169]
Hello, I'm now using SikuliLibrary and I think it is amazing, many thanks for the contributor.
But I have a question, how to click the exactly text while using the keyword "Click Text "?
You know sometimes, there are duplicate texts in the screen and I don't mean to click the first one at every time.
Thanks !

**Comment by rainmanwy** [comment]
you may set region firstly.
https://github.com/rainmanwy/robotframework-SikuliLibrary/blob/56a163f3f05bf80488c5fb0809d31db75c10c017/src/java/com/github/rainmanwy/robotframework/sikulilib/keywords/ScreenKeywords.java#L1145

then use "RegionClickText" keyword

**Comment by JerryXinhui** [comment]
Many thanks to your quick reply, But when I use RegionClickText, remind me "No keyword with name 'RegionClickText' found."
my version is robotframework-SikuliLibrary-2.0.0, I checked it is the latest version. Did I do someting wrong or something else?  
Thanks!

**Comment by rainmanwy** [comment]
maybe it is not uploaded to pypi yet.
you may have a try with main branch.

I plan to update pypi version recently.

**Comment by JerryXinhui** [comment]
Yeah,  many thanks to you and you are the **yyds**.
I will have a try later on.

**Comment by JerryXinhui** [comment]
tried with robotframework-SikuliLibrary==2.0.1  works well,  many thanks to the author!
