### ISSUE TITLE
[Errno 61] Connection refused - on Mac

### ISSUE THREAD

**Issue by mzbedat** [rainmanwy/robotframework-SikuliLibrary#17]
Hi,
I'm trying to run sikuli on Mac slaves (I have it working on windows slaves), but am getting connection refused error!

>###############  Running Test Suite: iOS_StreamVideo - Darwin 15.6.0 (PAs-Mac.local)  ###############
[ WARN ] Imported library '/Users/padmin/Documents/workspace/PeerApp_Automation/resources/sql.py' contains no keywords.
[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:49706/ failed: [Errno 61] Connection refused
[ ERROR ] Error in file '/Users/padmin/Documents/workspace/<My Project>/Keywords/iOS_StreamVideo_Keywords.txt': Initializing test library 'SikuliLibrary' with no arguments failed: Failed to get_keyword_names!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 41, in __init__
    self.remote = self._connect_remote_library()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 138, in _connect_remote_library
    self._test_get_keyword_names(remote)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 155, in _test_get_keyword_names
    raise RuntimeError('Failed to get_keyword_names!')

The error of no arguments is not the real cause, even after giving it (despite I didn't need to do it in windows) am still getting:

>[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:49758/ failed: [Errno 61] Connection refused
[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:49758/ failed: [Errno 61] Connection refused
[ ERROR ] Error in file '/Users/padmin/Documents/workspace/<My Project>/Keywords/iOS_StreamVideo_Keywords.txt': Initializing test library 'SikuliLibrary' with no arguments failed: Failed to get_keyword_names!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 41, in __init__
    self.remote = self._connect_remote_library()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 138, in _connect_remote_library
    self._test_get_keyword_names(remote)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 155, in _test_get_keyword_names
    raise RuntimeError('Failed to get_keyword_names!')

**Comment by mzbedat** [comment]
**STDERR**::

> WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)

**STDOUT**::

>0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Mapped path / to library com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.
3 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server starting
3 [main] INFO org.eclipse.jetty.server.Server  - jetty-7.x.y-SNAPSHOT
104 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - started o.e.j.s.ServletContextHandler{/,null}
369 [main] INFO org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:50169
371 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server started on port 50169.
*** classpath dump 
  0: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SikuliLibrary/lib/SikuliLibrary.jar
*** classpath dump end
[error] RunTimeINIT:  *** terminating: libs to export not found on above classpath: /sikulixlibs/mac/libs64

I'll investigate this:

>_[error] RunTimeINIT:  *** terminating: libs to export not found on above classpath: /sikulixlibs/mac/libs64_

**Comment by mzbedat** [comment]
Resolved:

1) installed maven and added it to my $PATH ($JAVA_HOME was missing as well - not sure its related but I added it)
2) downloaded the robot framework-sikulilibrary to my eclipse, and:
   mvn install
3) then: python setup.py install

**Comment by rainmanwy** [comment]
So the previous version is installed from pypi?

Pypi has only the version for Windows. Mac version is not packaged and released in pypi. So user have to use maven to package themselves.

**Comment by mzbedat** [comment]
Yes, I realized that.
Thanks.
