### ISSUE TITLE
KW Image Count does not work on version 2.0.1

### ISSUE THREAD

**Issue by douradojean** [rainmanwy/robotframework-SikuliLibrary#171]
Hello everyone.
I'm trying to use Image Count on my tests but it does not work.
The return message is _java.lang.IllegalArgumentException: wrong number of arguments_
![image](https://user-images.githubusercontent.com/81119420/142667446-4bbf65a5-7c54-4811-967d-2513f443a48a.png)
This only happen on version 2.0.1, in 2.0.0 version everything works fine.

**Comment by rainmanwy** [comment]
Hello,
Could you upgrade to 2.0.2.

I found there is a problem in this keyword. The root cause is i upgrade version of some dependency packages, and these package may have more strict check. and this keyword configured wrong args with "ArgumentNames" annotation.

Sorry for that!
