### ISSUE TITLE
Drag And Drop can not find srcImage eventhough image can be found by Wait Until Screen Contain

### ISSUE THREAD

**Issue by trinhttp** [rainmanwy/robotframework-SikuliLibrary#176]
I am trying to have a simple Sikuli script which drag an image from desktop to a chatbox. 

```
Wait Until Screen Contain         image=image_on_desktop_icon.png          timeout=${timeout}
Drag And Drop      srcImage=image_on_destop_icon.png     targetImage=input_message.png
```

Error: 
com.github.rainmanwy.robotframework.sikulilib.exceptions.TimeoutException: Timeout happened, could not find P(image_on_destop_icon.png -- not valid!) S: 0.8999999761581421 |

**Comment by rainmanwy** [comment]
Could you attach the detailed logs.
At least, “wait until screen contain” and “drag and drop” use same internal “wait” method.
Whether the element will change color at runtime?

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月27日 15:16
收件人: ***@***.***>
抄送: ***@***.***>
主题: [rainmanwy/robotframework-SikuliLibrary] Drag And Drop can not find srcImage eventhough image can be found by Wait Until Screen Contain (Issue #176)


I am trying to have a simple Sikuli script which drag an image from desktop to a chatbox.

Wait Until Screen Contain         image=image_on_desktop_icon.png          timeout=${timeout}



Drag And Drop      srcImage=image_on_destop_icon.png     targetImage=input_message.png



Error:
com.github.rainmanwy.robotframework.sikulilib.exceptions.TimeoutException: Timeout happened, could not find P(image_on_destop_icon.png -- not valid!) S: 0.8999999761581421


―

**Comment by trinhttp** [comment]
I captured another image and now it works like a charm!

I change from this one
![chat_panda_image_on_desktop_icon](https://user-images.githubusercontent.com/66866054/170656319-d0cedd37-0418-425b-8c4e-d312d6deeac6.png)
to this
![chat_panda_image_on_desktop_ui](https://user-images.githubusercontent.com/66866054/170656369-afea8306-63f7-445e-ab36-39f4422610bb.png)
