### ISSUE TITLE
how sikuli can find this image even if the image is altered?

### ISSUE THREAD

**Issue by abioneperhobby** [rainmanwy/robotframework-SikuliLibrary#18]
Hi,

thank for sikuli, it is awesome.

i make a test with the notepad demo. i stored the img of my windows and everything works well.

then i need to understand what happens if the image is not found.

as you can see in the video https://www.youtube.com/watch?v=1kZiqf2JCW4&feature=youtu.be  , my "windows start button" was corrupted changing color with Paint but sikuli find it anyway. why?

![windows_start_menu](https://cloud.githubusercontent.com/assets/2149815/20621668/a34e3386-b2ff-11e6-8776-bc053e53437d.png)

**Comment by abioneperhobby** [comment]
i generate the problem only using paint.net . maybe i'm changing alpha channel of the png as i reported here https://github.com/myint/perceptualdiff/issues/12

**Comment by rainmanwy** [comment]
Hi,
As sikuli image recognition is implemented based on OpenCV, i could find the answers from sikuli project.
https://answers.launchpad.net/sikuli/+question/213556
http://docs.opencv.org/2.4/modules/imgproc/doc/object_detection.html#matchtemplate
https://answers.launchpad.net/sikuli/+question/256236

And you could use keyword "Get Match Score" to get match score.
