### ISSUE TITLE
Improve linux installation documentation (someone can help me to install?)

### ISSUE THREAD

**Issue by abioneperhobby** [rainmanwy/robotframework-SikuliLibrary#19]
Hi,

i'm installing robotframework-sikulilibrary on linux mint.

i'm a newbie of manual maven/python installation and i have some problems.

Here

https://github.com/rainmanwy/robotframework-SikuliLibrary#pip-installation

i read to download the linux version from https://pypi.python.org/pypi/robotframework-SikuliLibrary , but there i read that the jar is not provided so i need to build it with maven, then i understand to return back to

https://github.com/rainmanwy/robotframework-SikuliLibrary#build-with-maven

and build manually with maven. 

Question number one : one the previous step send me to pypi if pypi send me to manual installation by maven? maybe documentation should avoid to send me to pypi?

then, i proceed following "build with maven" step.

1) cloning
2) build with maven

mvn package

due mvn package fails , i install the java jdk with apt-get install default-jdk

now maven build the package.

following the instructions, 

> - One zip file will be created in "target" folder, could unzip this file and add to PYTHONPATH
> - If want to installed to python, please execute

should i do both operation, or the second will automatically move the file to the PYTHONPATH?

i think the manual move is not necessary because

`/usr/local/lib/python2.7/dist-packages/SikuliLibrary/lib/SikuliLibrary.jar`

now exists.

so, when i run a simple test that on Windows works,

i obtain that the server is not running on a ... random port.

i can run the server on a port as described in the documentation, for example in port 10000 , but when i run robot again, no server is listening on ... another port.

`[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:40500/ failed: [Errno 111] Connection refuse`

```
java -jar /usr/local/lib/python2.7/dist-packages/SuliLibrary/lib/SikuliLibrary.jar 40500 .
0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Mapped path / to library com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.
1 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server starting
1 [main] INFO org.eclipse.jetty.server.Server  - jetty-7.x.y-SNAPSHOT
37 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - started o.e.j.s.ServletContextHandler{/,null}
120 [main] INFO org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:40500
121 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server started on port 40500.
```

```
robot visual.robot 
[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:52939/ failed: [Errno 111] Connection refused
```

should i manually set a port during import phase as described here http://rainmanwy.github.io/robotframework-SikuliLibrary/doc/SikuliLibrary.html ?

why in Windows this is not necessary?

thanks for your help,

then, when i understand a bit more, i will propose a documentation commit.

**Comment by rainmanwy** [comment]
Hi, 

Sorry to let you confused.

For installation, i upload window version(64bit) and linux version(64bit).

1. 

if your environment is ok, could download from pypi and install it directly(the jar file is included). The steps are:

- unzip file
- Enter the folder, and execute "python setup.py install", then it should be installed to python lib"site-packages or dist-packages"

2.
If packages in pypi is not ok in your environment. Then you could package yourself.

- Clone this project, and execute `mvn package` 
- Execute `python setup.py install` to install it to python lib.

For library usage, there are two options

1. 
This library include python part and java part. If you want to use this library locally(robot python process and sikuli java process are on same testing server), you could import SikuliLibrary in your robot cases directly. And library will choose a free tcp port

2.
If yours robot python process and sikuli java process are running on different machine(Consider that robot cases are executing on one linux server, and you want to testing some applications on windows.), could deploy the jar file to target machine, and use "Remote" library in robot to connect to sikuli java process and executing related keywords.
About this, you could check [https://github.com/robotframework/RemoteInterface](url) to get more details.

I am not sure whether it is clear to you. Any questions, no hesitate to tell me. thank you very much!

**Comment by abioneperhobby** [comment]
@rainmanwy i understand, thanks.

the environment can be not ok if, for example, we are running on a mac, or a 32 bit or linux, or so on, right?

and thanks for your awesome work.

**Comment by abioneperhobby** [comment]
@rainmanwy for linux connection problem , i created a new issue. https://github.com/rainmanwy/robotframework-SikuliLibrary/issues/20
