### ISSUE TITLE
connection remote (localhost) server failed.

### ISSUE THREAD

**Issue by abioneperhobby** [rainmanwy/robotframework-SikuliLibrary#20]
I create a very simple robot that runs on microsoft windows.

Now i need to create the same example in Linux Environment, ( linux mint )

I installed sikuli from maven and sikuli server can run if i manually run it, but robot framework is not able to connect to sikuli jar.

everything (robot framework, jar and sikuli library) runs on the same machine

if i run without super user permission i obtain : 

```
[ ERROR ] Error in file '/home/qa-asus/Desktop/automatictestingtool/robotframework/THRON/Player/Customers/commons.robot': Initializing test library 'SikuliLibrary' with no arguments failed: Start sikuli java process failed!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 40, in __init__
    self._start_sikuli_java_process()
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 97, in _start_sikuli_java_process
    self._wait_process_started()
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 114, in _wait_process_started
    raise RuntimeError('Start sikuli java process failed!')
```

if i run with super user permission i obtain

```
[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:42707/ failed: [Errno 111] Connection refused
[ ERROR ] Error in file '/home/qa-asus/Desktop/automatictestingtool/robotframework/THRON/Player/Customers/commons.robot': Initializing test library 'SikuliLibrary' with no arguments failed: Failed to get_keyword_names!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 41, in __init__
    self.remote = self._connect_remote_library()
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 138, in _connect_remote_library
    self._test_get_keyword_names(remote)
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 155, in _test_get_keyword_names
    raise RuntimeError('Failed to get_keyword_names!')
```

what should i do to permit connection?

thanks.

**Comment by rainmanwy** [comment]
As described in doc.
`Note

For Linux, there are some dependencies need be installed, please check sikuli quick start to get more details.`

I am not sure whether you have installed depended packages in your linux server. You may check this link [http://www.sikulix.com/specials/files/linux-setup-prerequisites.html](url).
And also you could start java process manually, the console will log some details. The command should be like:
`java -jar SikuliLibrary.jar  <port>  <captured_imagine_folder>`.

**Comment by abioneperhobby** [comment]
after installing 

sudo apt install libopencv-dev
sudo apt install tesseract-ocr

the connection works.

sorry @rainmanwy , i thought that the connection refused was another kind of problems.

thanks.

**Comment by abioneperhobby** [comment]
@rainmanwy in a official windows 10 virtual machine, i installed python 2, robotframework, and sikuli built with maven. 

This is my environment

robot --version
Robot Framework 3.0.2 (Python 2.7.14 on win32)

java --version
java 9
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

C:\src\automatictestingtool\robotframework\THRON\Player\ce1>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
certifi (2017.7.27.1)
chardet (3.0.4)
decorator (4.1.2)
idna (2.6)
pip (9.0.1)
requests (2.18.4)
robotframework (3.0.2)
robotframework-requests (0.4.7)
robotframework-selenium2library (1.8.0)
robotframework-SikuliLibrary (DEV)
selenium (3.6.0)
setuptools (28.8.0)
urllib3 (1.22)

if i manually start a server, it works

C:\src\automatictestingtool\robotframework\THRON\Player\ce1>java -jar c:\Python27\Lib\site-packages\SikuliLibrary\lib\SikuliLibrary.jar 50000 c:\captured\
0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Mapped path / to library com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.
0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server starting
0 [main] INFO org.eclipse.jetty.server.Server  - jetty-7.x.y-SNAPSHOT
170 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - started o.e.j.s.ServletContextHandler{/,null}
437 [main] INFO org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:50000
437 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server started on port 50000.

but launching from robot framework, connection to localhost are denied. 

robot api_events.robot
[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:49755/ failed: <Fault 0: 'Failed to invoke method get_keyword_names in class org.robotframework.remoteserver.servlet.ServerMethods: java.lang.RuntimeException'>
[ ERROR ] Error in file 'api_events.robot': Initializing test library 'SikuliLibrary' with no arguments failed: Failed to get_keyword_names!
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\SikuliLibrary\sikuli.py", line 56, in __init__
    self.remote = self._connect_remote_library()
  File "c:\python27\lib\site-packages\SikuliLibrary\sikuli.py", line 157, in _connect_remote_library
    self._test_get_keyword_names(remote)
  File "c:\python27\lib\site-packages\SikuliLibrary\sikuli.py", line 174, in _test_get_keyword_names
    raise RuntimeError('Failed to get_keyword_names!')

now i learned how to make pull request, so i will improve documentation to help others like me. Can you help your italian nightmare? :) thanks.

**Comment by abioneperhobby** [comment]
@rainmanwy i think i solved.
i removed java runtime 9 and installed java runtime 1.8
when windows firewall asked me to authorize connection, i also checkec "authorize localhost connection" so now i don't know if problem was java version or windows firewall, but i think windows firewall. Do you agree?
