### ISSUE TITLE
Drag and Drop in Sikuli; Can anybody help me for drag and drop by Offset using Sikuli.

### ISSUE THREAD

**Issue by lokmanliton** [rainmanwy/robotframework-SikuliLibrary#23]
Drag and Drop By Offset is available in Selenium2Library, but I need on SikuliLibrary as well,
 - I have to click on image and it needs to drag and drop to specific coordinate on an windows application. It is not possible using 'Drag and Drop' keywords as there is no specific target image. Like I want to draw a straight line on a graph.
![14by14 axes](https://cloud.githubusercontent.com/assets/10383103/21589098/805d7fb2-d118-11e6-9549-d89bdc8aa002.jpg)

Could you please help me, I am stack on here,
Thanks in Advance.

**Comment by rainmanwy** [comment]
from the sikuli java doc, this could be implemented.
http://nightly.sikuli.de/docs/org/sikuli/script/Location.html
So you want to use offset, or location in screen?

the keyword is implemented in https://github.com/rainmanwy/robotframework-SikuliLibrary/blob/master/src/java/com/github/rainmanwy/robotframework/sikulilib/keywords/ScreenKeywords.java

Could you have a try to implement this keyword yourself, and raise PR to me. As i haven't enough time to continue maintain this library recently. Sorry about that.

**Comment by rainmanwy** [comment]
`@RobotKeyword("Drag the source image to target by offset.\nIf source image is empty, drag the last match and drop at given target")
    @ArgumentNames({"srcImage", "xOffset", "yOffset"})
    public void dragAndDropByOffset(String srcImage, int xOffset, int yOffset) throws Exception {
        int result = 0;
        Match srcMatch;
        if ( "".equals(srcImage) ) {
            srcMatch = screen.getLastMatch();
            if(srcMatch == null) {
                throw new ScreenOperationException("Please input srcImage");
            }
        } else {
            srcMatch = wait(srcImage, Double.toString(this.timeout));
        }
        int newX = srcMatch.getX() + xOffset;
        int newY = srcMatch.getY() + yOffset;
        Location newLocation = new Location(newX, newY);
        result = screen.dragDrop(newLocation);
        if (result==0) {
            capture();
            throw new ScreenOperationException("Failed to drag "+srcImage+" to " +newLocation);
        }
    }`

I have added a keyword for this, could you have a try this new keyword.

Thank you very much!
