### ISSUE TITLE
how to deactivate sikuli_java_stderr_timestamp.txt

### ISSUE THREAD

**Issue by abioneperhobby** [rainmanwy/robotframework-SikuliLibrary#26]
for every run,
sikuli build a txt file as Sikuli_java_stderr_1487606174.96.txt
how can i deactivate it?

thanks.

**Comment by rainmanwy** [comment]
sorry, it is not configurable yet.
Maybe i could add a option in __init__ to disable it. How do you think?

**Comment by abioneperhobby** [comment]
It can be usefull,  thanks

Il 06 Mar 2017 06:10, "Rainmanwy" <notifications@github.com> ha scritto:

**Comment by rainmanwy** [comment]
@abioneperhobby , you may have a try the latest version, and disable the log files through config environment variable "DISABLE_SIKULI_LOG", this is described in document.

**Comment by abioneperhobby** [comment]
@rainmanwy 
robotframework-SikuliLibrary (0.1.5) looks the last version but i don't know if
C:\Python27\Lib\site-packages\SikuliLibrary\lib\SikuliLibrary.jar is the last version that can be found here https://launchpad.net/sikuli/sikulix/1.1.1
i tried to install, but i don't know what to choose here

![image](https://cloud.githubusercontent.com/assets/2149815/24903809/cddbc986-1eae-11e7-97d6-033088bbf4f1.png)


by the way in windows i try to do

set DISABLE_SIKULI_LOG=yes
but nothing changed.

can you help me again? thanks.

**Comment by rainmanwy** [comment]
i did not upload the latest version to pypi. Could you checkout the latest version from github and package yourself? Actually you do not need download sikuli installer, all needed java libs are in maven repo.

**Comment by abioneperhobby** [comment]
@rainmanwy i installed the github version (DEV) and now using 
set DISABLE_SIKULI_LOG=yes 
no txt file is produced.

thanks.

**Comment by louislewatcn** [comment]
@abioneperhobby, Hi , I have the same problem, would youi please tell me where to set DISABLE_SIKULI_LOG=yes in Win10?
