### ISSUE TITLE
 No keyword with name 'Set Ocr Text Read'

### ISSUE THREAD

**Issue by HelioGuilherme66** [rainmanwy/robotframework-SikuliLibrary#27]
When trying to get text recognition I get the error:
`20170301 11:54:49.772 :  FAIL : No keyword with name 'Set Ocr Text Read' found.`

I was trying the keyword `Double Click` and got the error:
`[error] Image: Image not valid, but TextSearch is switched off!`

**Comment by rainmanwy** [comment]
Do you install this library through pip?
i haven't update the lib in pypi a long time. So some keywords may missed.

**Comment by HelioGuilherme66** [comment]
You are correct.
The keyword exists when built from github project.
(Closing, although I have no success in text recognition)
