### ISSUE TITLE
java command can fail in Windows with spaces between paths

### ISSUE THREAD

**Issue by jpeltonen** [rainmanwy/robotframework-SikuliLibrary#29]
```
def _start_sikuli_java_process(self):
        libFolder = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'lib')
        jarList = glob.glob(libFolder+os.sep+'*.jar')
        if len(jarList) != 1:
            raise Exception('Sikuli jar package should be exist in lib folder')
        sikuliJar = jarList[0]
        command = 'java -jar '+sikuliJar+' %s %s' % (str(self.port), self._get_output_folder())
        process = Process()
        process.start_process(command, shell=True, stdout=self._output_file(), stderr=self._err_file())
        self.logger.info('Start sikuli java process on port %s' % str(self.port))
        self._wait_process_started()
        self.logger.info('Sikuli java process is started')
```

sikuliJar can be on path that has empty spaces like C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\SikuliLibrary\lib\SikuliLibrary.jar

In Windows it should be command using double quotes around sikuliJar = 'java -jar '+'\"' + sikuliJar + '\"'+' %s %s' % (str(self.port), self._get_output_folder())

Don't know is it needed only in Windows and how to detect it.

**Comment by rainmanwy** [comment]
@jpeltonen , thanks for this finding.
Now i use "arguments" option to try to fix this problem.

you may have a try with the latest version"
