### ISSUE TITLE
A way to change Settings.MinSimilarity

### ISSUE THREAD

**Issue by JediMaster93** [rainmanwy/robotframework-SikuliLibrary#3]
Hi,
Great library but I've been having issues with "Screen Should Contain" giving out false positives.
I think if I could set Settings.MinSimilarity to about 0.9 that it would fix my issues.
Could you implement it or perhaps provide a workaround?

Thanks

**Comment by rainmanwy** [comment]
Hi, 

Thank you very much. I really haven't notice "Settings".

I have checked the implementation. Seems this options could work at runtime.
I could have a try it. Have you compile in your local environment about this lib?

**Comment by JediMaster93** [comment]
Thanks!
I havent compiled  yet. 
Im pretty confused with the structure of the code, I only wrote simple python libraries for robot framework.

**Comment by rainmanwy** [comment]
OK, could you send me source image and target image, so that i could tested myself?

**Comment by JediMaster93** [comment]
Source:
![source](http://i.imgur.com/ZQtIsSQ.png)
Target:
![target](http://i.imgur.com/egA80jZ.png)

heres the test I did:
Open first image in paint or something else
and run

   `Add Image Path    ${CURDIR}${/}sikuli_resources`
    `Screen Should Not Contain    targetImage.png`

In my case "Screen should not contain" fails because it matches the 2 similar parts, but they have different numbers.
 I hope that with Setting.MinSimilarity=1 or 0.9 it would not match and keyword would pass.

**Comment by JediMaster93** [comment]
Any progress on your end?
I managed to compile and I added a method:
```
    @RobotKeyword("test")
    @ArgumentNames({"value"})
    public void setMinSimilarity(double similarityValue) {
		org.sikuli.script.Settings.MinSimilarity = similarityValue;
	}
```
But I get Compilation Errors

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.637 s
[INFO] Finished at: 2016-05-04T14:51:06+02:00
[INFO] Final Memory: 12M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project robotframework-SikuliLibrary: Compilation failure
[ERROR] /D:/git/robotframework-SikuliLibrary/src/java/com/github/rainmanwy/robotframework/sikulilib/keywords/ScreenKeywords.java:[283,34] cannot find symbol
[ERROR] symbol:   class Settings
[ERROR] location: package org.sikuli.script
```

Weird since I see [in java doc](http://doc.sikuli.org/javadoc/   ) that it should exist.
Any ideas?

**Comment by rainmanwy** [comment]
That's great if you could compile yourself.
http://nightly.sikuli.de/docs/index.html

"Settings" should be imported like:
`import org.sikuli.basics.Settings;`

With your example, unfortunately i could not re-produce it.

You could add keyword like:
`    @RobotKeyword("test")
    @ArgumentNames({"similarityValue"})
    public void setMinSimilarity(String similarityValue) {
        
        org.sikuli.basics.Settings; = Double.parseDouble(similarityValue);
    }`

If it works in your environment, then we could add this keyword to this lib.

btw, do you use pip to install this library? So you are using Windows to run test, right?
if everything is ok, i could upload to pypi.

Thank you very much!

**Comment by rainmanwy** [comment]
I have add this keyword
https://github.com/rainmanwy/robotframework-SikuliLibrary/blob/master/src/java/com/github/rainmanwy/robotframework/sikulilib/keywords/SettingsKeywords.java

I am sorry, i mis-understand your points:).
I have tested it with your images, everything looks ok.

You could get the latest version from github, and package yourself.

**Comment by JediMaster93** [comment]
Awesome man! You're the best!
I'll try this out right now.

Yesterday I was messing around with match.getScore(), which returns accuracy for the match.
Seems like it could be really usefull combined with MinSimilarity, so I'll do some tests with it and send you a pull request if it turns out useful.


Yes,I was using pip at first, but yesterday I used maven. Im working on windows but I will probably use it on Ubuntu 14.04 as well.

**Comment by rainmanwy** [comment]
ok. Wait your update:)

**Comment by JediMaster93** [comment]
Hi @rainmanwy ,

I tried out my tests that gave me false positives yesterday and now they work perfectly when i set minSimilarity to very high.

Thanks so much for you help!

**Comment by rainmanwy** [comment]
Good to hear that:)
You are welcome!
