### ISSUE TITLE
"Some windows should contain"

### ISSUE THREAD

**Issue by abioneperhobby** [rainmanwy/robotframework-SikuliLibrary#30]
Hi,

**Screen Should Contain** works only if the image sikuli is looking for is on foreground.

There is a way to make the same check in the application windows?

in my use case, the browser contains the image i'm looking for, but if browser is not in the foreground when sikuli runs, the test will fail.

thanks.

**Comment by rainmanwy** [comment]
this is a limitation of sikuli. sikuli could automate all things in screen, this is a advantage, and ata shortage at the same time. BTW, if it is a web page, selenium is a better testing tool for web testing.

**Comment by jpeltonen** [comment]
You could start browser maximized 
Example:
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --start-maximized

You can also use tools like AutoIt to maximize and minimize application Windows.
see https://www.autoitscript.com/autoit3/docs/functions/WinSetState.htm

There is AutoIt library for Robot Framework Python installation at least. Couldn't get AutoIt library working with IronPython https://github.com/sjia/robotframework-autoitlibrary

**Comment by abioneperhobby** [comment]
@rainmanwy thanks
i use selenium a lot for testing, but with sikuli i can make a visual check of what my browser is rendering.

**Comment by abioneperhobby** [comment]
@jpeltonen there is also the keyword in robot framework to maximize window.
