### ISSUE TITLE
No keyword with name 'Drag And Drop By Offset' found.

### ISSUE THREAD

**Issue by anttisal** [rainmanwy/robotframework-SikuliLibrary#31]
Hi,

I have a problem as there seems to be several keywords in the documentation (http://rainmanwy.github.io/robotframework-SikuliLibrary/doc/SikuliLibrary.html) that are not found when running the test, for example "Drag And Drop By Offset" and "Wait for image".
I have installed the latest version of the library (0.1.5) and running RobotFramework 3.02.

Could it be that the jar file is not up to date?

**Comment by rainmanwy** [comment]
@anttisal , the latest version is not uploaded to pypi.
You could get source code from GitHub, and package yourself.

**Comment by anttisal** [comment]
Thank you for the information.
Could there be a comment in the readme that jar file comes with the library, but one needs to compile the newest version.

**Comment by rainmanwy** [comment]
Maybe i could mentioned in "pip" chapter that pypi version is not latest version.
Actually "maven method" is mentioned in readme yet.

How do you think?

**Comment by anttisal** [comment]
Yes, I think the pip chapter is good place for it.
I did notice the maven method, at first I thought it was an alternative way of taking the library in use :)
Thank you.

**Comment by rainmanwy** [comment]
@anttisal . i have updated README. Thank you for your suggestion.
