### ISSUE TITLE
i think java process will never be terminated

### ISSUE THREAD

**Issue by abioneperhobby** [rainmanwy/robotframework-SikuliLibrary#32]
i'm doing a lot of work with robot framework and sikuli.

everytime a step of a test fails, i run the test again.

after some time, Windows alerts me that ram is running low.

taking a look at the process manager, i think java process is never terminated as you can see.

![image](https://cloud.githubusercontent.com/assets/2149815/25043999/4569ffc8-2124-11e7-8f2b-30d1f1f5a72c.png)

there is also a lot of cmd.exe process opened, but in windows i use only ONE terminal window at time

![image](https://cloud.githubusercontent.com/assets/2149815/25044012/5388a1d6-2124-11e7-81ab-8a1d1031150a.png)

maybe sikuli should check if there are any server avaiable before creating another one?

how i can try to debug this issue?

thanks.

**Comment by abioneperhobby** [comment]
i'm making some test with mode=DOC
Library             SikuliLibrary       timeout=30      mode=DOC

**Comment by rainmanwy** [comment]
@abioneperhobby , have you called "stop remote server" in suite teardown?

If you want to just use one java process, "REMOTE" mode could be used. And you could start java process spearately, and "stop remote server" should not be used with "REMOTE" mode.

**Comment by abioneperhobby** [comment]
i never used stop remote server and i never started server manually.

should sikulilibrary check if a server is avaiable and re-use it or should i manually start a remote server manually?

avoid manual operation can be preferred.

thanks

**Comment by rainmanwy** [comment]
@abioneperhobby , "stop remote server" must be used in teardown.
https://github.com/ombre42/jrobotremoteserver/wiki/Getting-Started#Stopping_the_Server

about remote mode, that mean the java process is not created when SikuliLibrary is init by RF, the java process is started manually or through script. 

the remote server could be re-use, but still you need to stop it with keyword or other methods.

**Comment by abioneperhobby** [comment]
@rainmanwy thanks a lot.
