### ISSUE TITLE
Feature Request: Remove Image Path

### ISSUE THREAD

**Issue by ChthonicOne** [rainmanwy/robotframework-SikuliLibrary#36]
I've figured out how you did it. You're using a collection of image paths to do this. I would like to request a Remove Image Path keyword that will either remove an image path from it's list, or throw an exception if the image path is not in the list.

This would assist when there are multiple files with similar names in different paths if the all get thrown into the path collection. We could remove them when we were done with them.

Thank you for your response.

<strike through>If I were to run this keyword a second time in a script, what would happen?

Would it overwrite the previous image path, or would it append to it? Does it return the previous path?

I'm asking because I want to set each of my keywords to have it's own path for their images, but I don't want to type out each of their paths each time I pass one of the images. If it were to overwrite the path if I call it a second time and pass back the previous path, it would help me immensely.

Thanks for your response. </strike through>

**Comment by rainmanwy** [comment]
Yes, "remove" keyword is needed. Thanks!

**Comment by rainmanwy** [comment]
@ChthonicOne , "remove image path" keyword is implemented. You may have a try.

**Comment by ChthonicOne** [comment]
Is this change committed to the master or to a branch? I don't see any commits to anything other than the documentation yet.

I do appreciate your assistance though.

**Comment by rainmanwy** [comment]
Sorry, you could try again.

**Comment by ChthonicOne** [comment]
Yes, now it works great. Thank you. This issue is now closed.
