### ISSUE TITLE
how to debug sikuli failure (maybe taking a full page screenshot on failure?)

### ISSUE THREAD

**Issue by abioneperhobby** [rainmanwy/robotframework-SikuliLibrary#37]
this is not an issue, is much more a help request.

i have a test that use sikuli.

my test open a browser with selenium2library and use sikuli in order to find and click some elements.

by jenkins, i schedule the execution of the same test every 10 minutes.

the test runs in a stand alone laptop that any one use with only robot framework, jenkins and the test.

the test normally works, but sometime it fails

![image](https://cloud.githubusercontent.com/assets/2149815/25886684/111c5a8c-355f-11e7-91c7-42a311be8efe.png)

i would be able to see what there is on the screen when the test fail, but in the log i have nothing useful.

as you can see, the image path is not found

![image](https://cloud.githubusercontent.com/assets/2149815/25886771/6f67be60-355f-11e7-9ca9-1891b4a84fd2.png)

the image path is http://localhost:8080/job/cloudconvert/102/robot/report/sikuli_captured/sikuliximage-1494400773412.png

but there is any captured image here

![image](https://cloud.githubusercontent.com/assets/2149815/25887352/1f65b8ba-3562-11e7-97e3-27666e80685f.png)

This is the configuration

![image](https://cloud.githubusercontent.com/assets/2149815/25887388/3e2f3492-3562-11e7-83ed-4433618a80b4.png)

Normally there are image in the previous folder,

but in order to create this ticket i delete all because i'm never be able to find the image related with the log. 

i know that should be a jenkins question and not a sikuli related one, but should i setup a webserver ?

there is also a way to set a "capture full page screenshot" on failure?

thanks for those advices,

i would to create a wiki page for sharing suggestion

**Comment by rainmanwy** [comment]
Hi, @abioneperhobby 
Be default, captured images should be stored in RF output folder. 
`    def _get_output_folder(self):
        outputDir = os.path.abspath(os.curdir)
        try:
            outputDir = BuiltIn().get_variable_value('${OUTPUTDIR}')
        except Exception, err:
            pass
        return outputDir
`
And in robot html log, i assume that robot html log file is also in OUTPUTDIR.
`    private void capture() {
        ScreenImage image = screen.capture();
        String imagePath = image.save(CaptureFolder.getInstance().getCaptureFolder());
        System.out.println("*DEBUG* Saved path: "+imagePath);
        File file = new File(imagePath);
        String fileName = file.getName();
        System.out.println("*HTML* <img src='" + CaptureFolder.getInstance().getSubFolder() + "/" + fileName + "'/>");
    }
`

And also you could use keyword "setCaptureFolder", to set folder which is used to store captured images.

And when execute robot case through pybot, you could use option "-L Trace", and more information could be logged to robot html report. As you can see, "capture" method will print save path with DEBUG level.

**Comment by HelioGuilherme66** [comment]
@abioneperhobby,

In your case, the problem is that Jenkins is not finding the files.

In my Jenkins setup, I run a batch file:
```
cd \Testes\CAMB
robot -d "%WORKSPACE%\%BUILD_ID%" login.robot
```
And I have the Build step configured to copy all Sikuli files:
![jenkins_sikuli_build_step](https://cloud.githubusercontent.com/assets/2866630/25890479/80d83b10-3565-11e7-89c9-3aab31aa20f6.png)

And so the log and report shows all the files:
![example_jenkins_sikuli](https://cloud.githubusercontent.com/assets/2866630/25890512/9ddf35a6-3565-11e7-8fbf-93d89c877916.png)

**Comment by abioneperhobby** [comment]
@HelioGuilherme66 thanks,
i'm on ubuntu and the jenkins is loaded by a jar,
in "Publish Robot Framework Tests Result" i already put * to "Other File To Copy" and this works with Selenium2library captured image in case of failure.

I think i should not need to manually move file using jenkins. i'm wrong?

thanks.

**Comment by abioneperhobby** [comment]
with your advices i understand what is going wrong.

my jenkins war is inside a folder and the folder is the jenkins home.

Scrivania = Desktop in italian.

/home/quality/Scrivania/jenkins/

when i start jenkins, i set the container folder as jenkins home

java -jar -DJENKINS_HOME=. jenkins.war

so every time the Robot Framework Plugin will publish test results, it will publish inside

/home/quality/Scrivania/jenkins/jobs/<jobName>/builds/<buildName>

but sikuli will publish output in the sikuli_captured folder ,

and when you will configure "Publish Robot Framework Tests Results" with "*" , the subfolder is not included, so you need to set also sikuli_captured/*

![image](https://cloud.githubusercontent.com/assets/2149815/25902432/cbbbbcf4-3599-11e7-9410-f9b07690bebb.png)

now, to permit robot framework plugin to find the basepath of the test, i also set the path of my .robot file

![image](https://cloud.githubusercontent.com/assets/2149815/25902493/f7185fd8-3599-11e7-9b12-412b8d74334f.png)

Due sikuli will every time add image to sikuli_captured folder, i will clean the folder before the test runs.

cd /home/quality/Src/automatictestingtool/robotframework/THRON/Player/Contents/pdf/
rm -f *.txt
rm -f sikuli_captured/*.png
python2 -m robot pdf.robot

this way, in the robot result there are the images.
