### ISSUE TITLE
Adding More Keywords

### ISSUE THREAD

**Issue by auyong** [rainmanwy/robotframework-SikuliLibrary#41]
Hi Rainmanwy,

     I am looking into using your SikuliLibrary to do some automation on the Windows platform with Robot and possibly adding more Keywords to the ScreenKeywords.java file. What is the best way to go about doing it?

     I tried getting a fork from here and creating a new executable jar but it did not seem to work...

Thanks,
auyong

**Comment by rainmanwy** [comment]
@auyong , could you provide more information.
Whether old keywords are still working? how about the error log?

**Comment by auyong** [comment]
@rainmanwy 
I am looking into extending the library with more capabilities. For example, the doubleClick method/keyword, takes only the image parameter. I would like to do something like doubleClick(image, offsetx, offsety) among other things. Another useful feature would be for the keywords to accept image matching percentage, which is supported by Sikuli but does not seem to be supported in this library.

Also, how do I contribute to this library? If I start writing new keyword and functionality, do I check in the code here for you to review? Would love to help if possible.

**Comment by rainmanwy** [comment]
if you done something, you could create pull requests to me.
And you could check https://github.com/robotframework/JavalibCore to learn how to implement java based keyword.

**Comment by auyong** [comment]
@rainmanwy 
Hello, I have added a doubleClick overload keyword that can take care of offsets and created a pull request. Please take a look.

**Comment by rainmanwy** [comment]
@auyong , thanks.
