### ISSUE TITLE
Run as Admin for Sikuli to Interact with Microsoft Management Console. Please add to Release Note/Readme.

### ISSUE THREAD

**Issue by auyong** [rainmanwy/robotframework-SikuliLibrary#43]
I would like to add a note that through my recent testing, that Microsoft Management Console (MMC) will not let SikuliX perform any actions on it, unless SikuliX itself is started as an administrator. If you are using SikuliX only, it is easy, just start SikuliX IDE or run the SikuliX script in a console that was started as an administrator (ie: right click on cmd/console and select "run as administrator"). However, if you are using the SikuliLibrary and Robot framework, SikuliLibrary itself also needs to be started from the cmd window that was "run as administrator". Otherwise, you will get a lot of errors like:

```
[log] CLICK on L(1061,118)@S(0)[0,0 1920x1080]
[error] RobotDesktop: checkMousePosition: should be L(1061,118)@S(0)[0,0 1920x1080]
but after move is L(137,215)@S(0)[0,0 1920x1080]
Possible cause in case you did not touch the mouse while script was running:
 Mouse actions are blocked generally or by the frontmost application.
You might try to run the SikuliX stuff as admin.
```

Besides the above log error, the symptom is that the mouse itself does not move and will never interact with the MMC UI.

I have also set my UAC to the lowest level (not to notify the user). This does not mean that UAC is turned off, just that it does not have any unnecessary popup when your tests are being run (or you will have to take care of them in your test scripts).

It would help to add these observations to the readme/release notes, maybe under a Microsoft Windows section.

**Comment by rainmanwy** [comment]
@auyong , thank you very much. Could you raise a pull request for it?

**Comment by auyong** [comment]
@rainmanwy 
Done. Please check and merge.
