### ISSUE TITLE
Different browsers different Colors. How to handle this situation?

### ISSUE THREAD

**Issue by abioneperhobby** [rainmanwy/robotframework-SikuliLibrary#48]
This is my situation 

Same website
Screenshot taken with Windows Snipping Tools
Every test use "Page Should Contain" screenshot on the screen.

If screenshot are taken viewing website with chrome and test are runned with chrome, everything works as aspected. Same in Firefox. But if i use firefox to search screenshot taken with chrome, image recognition fail. 

I understand that different browser renders colour in a little different way. In my case, grey color is a bit darker in Firefox.

To avoid this situation, i think i can Set Min Similarity a bit lover, but i prefer to avoid this approach to avoid false positive recognition.

Any suggestion?

thanks.

**Comment by rainmanwy** [comment]
@abioneperhobby , one workaround is capture these different images and named like <mybutton>_firefox.png, <mybutton>_chrome.png, then define a browser variable in RF.

if you are using selenium2library, i guess you have defined such variable already. so you could use it directly.

How do you think?

**Comment by abioneperhobby** [comment]
@rainmanwy i alredy do this. it works fine, even you must take a lot of screenshots. i think there is no other solutions.
