### ISSUE TITLE
Start sikuli java process failed! 

### ISSUE THREAD

**Issue by gupengism** [rainmanwy/robotframework-SikuliLibrary#56]
Hi,
I got error in one of two machine as below (one is work fine) kindly to suggest.

[ ERROR ] Error in file 'D:\Teleconsultation_refactor\qa-automation-teleconsulltation\TestScenarios\MyProfile_MyMedicalInfo_MyMedicalCases_Page.robot': Initializing test library 'SikuliLibrary' 
 with no arguments failed: Start sikuli java process failed! 

Traceback (most recent call last): 
  File "c:\Python27\lib\site-packages\SikuliLibrary\sikuli.py", line 54, in __init__ 
    self.start_sikuli_process(port) 
  File "c:\Python27\lib\site-packages\SikuliLibrary\sikuli.py", line 92, in start_sikuli_process 
    raise RuntimeError('Start sikuli java process failed!')

**Comment by rainmanwy** [comment]
Thanks!
Could you attach the log files here.
And how  do you install this library, through pypi or source installation?

**Comment by abioneperhobby** [comment]
if you are on Windows, i got the same error when Windows Firewall blocked INTERNAL java connection. so in windows firewall i  permitted every type of connection to the sikuli jar and it worked.

**Comment by gupengism** [comment]
Hi rainmanwy,

Thank you for your reply. I can resolve that by set java path to environment variable so i miss that. :)
