### ISSUE TITLE
[brainstorming]: "Take screenshot if Screen Should Contain fails"

### ISSUE THREAD

**Issue by abioneperhobby** [rainmanwy/robotframework-SikuliLibrary#58]
Use Case  

i'm searching for "image" in "page".

the check fail.

why?

recording a screenshot can be useful.

i create this keyword

```
Page Should Contain This Or Take Screenshot If Not Contain
	[Arguments]					${WHAT}
	${passed} =					Run Keyword And Return Status		Screen Should Contain		${WHAT}
	Log To Console				${passed}
	Run Keyword Unless			${passed}					Capture Page Screenshot			searching_${WHAT}.png	
```

so

1) i store the result of Screen Should Contain
2) if Screen Should Contain returns true, do nothing
3) if Screen Should Contain returns False, Capture Page Screenshot

this approach can be useful for other tester?

maybe we can another parameter to Screen Should Contain with the name of the screenshot to create if the check fails?

it can be useful to understand WHY a check is failing.

what do you think @rainmanwy ?

**Comment by rainmanwy** [comment]
@abioneperhobby , by default, keyword will capture the whole screen when it fail.

`
        Match match = find(image);
        if (match == null) {
            capture();
            throw new ScreenOperationException("Screen should contain "+image);
        }

private String capture() {
        ScreenImage image = screen.capture();
        String imagePath = image.save(CaptureFolder.getInstance().getCaptureFolder());
        System.out.println("*DEBUG* Saved path: "+imagePath);
        File file = new File(imagePath);
        String fileName = file.getName();
        System.out.println("*HTML* <img src='" + CaptureFolder.getInstance().getSubFolder() + "/" + fileName + "'/>");
        return fileName;
    }

`
And the abs path will be logged.
Is it not worked in your environment?

**Comment by abioneperhobby** [comment]
oh yes!.
my workflow is easier to understand because in my log i write
"not able to find <img> in <screen img>"
so i obtain this log

and the filename is related to the test name, easier to find if there are a lot of test

![image](https://user-images.githubusercontent.com/2149815/34296074-02963d0c-e711-11e7-868c-e2a7a602b6ed.png)

**Comment by rainmanwy** [comment]
Yes, it is not easy to get test name, and logged in sikuli java process.
So it could be handle in RF user keyword.
