### ISSUE TITLE
Sikuli or SikuliX

### ISSUE THREAD

**Issue by Tset-Noitamotua** [rainmanwy/robotframework-SikuliLibrary#6]
@rainmanwy Are you using the old Sikuli or the new SikuliX?

Cheers
Tset

**Comment by rainmanwy** [comment]
SikuliX 1.1.0
		<dependency>
			<groupId>com.sikulix</groupId>
			<artifactId>sikulixapi</artifactId>
			<version>1.1.0</version>
		</dependency>

**Comment by Tset-Noitamotua** [comment]
It is worth to mention it in readme and also to link to sikulix.com
Reason: some people think that Sikuli is close to end of life. At the same time they might be not aware of recent SikuliX so they might think that it is not wort using this library.

**Comment by rainmanwy** [comment]
Thanks for this suggestion.
So you mean http://sikulix.com/

**Comment by Tset-Noitamotua** [comment]
yes

**Comment by rainmanwy** [comment]
Ok, got it. Will update readme soon.
