### ISSUE TITLE
How to use "Input Text" with empty image?

### ISSUE THREAD

**Issue by romuluc** [rainmanwy/robotframework-SikuliLibrary#64]
When I use:
`Input Text    word:`

_Keyword 'SikuliLibrary.Input Text' expected 2 arguments, got 1._

**Comment by RaiMan** [comment]
Looking into the sources, it looks like you have to say:

`Input Text "" word:`

I am not sure wether this is syntactically correct.

`Input Text`according to the Keywords docs needs 2 parameters. The first one is the image to be clicked first, but this can be empty (means the second parameter is the text to be entered at the current focused cursor position).

So the trick is to leave the first parameter empty, however this has to be written in RFW slang.

**Comment by rainmanwy** [comment]
Thank you @RaiMan for your help:).
@romuluc , you could use RF built-in variable ${EMPTY}
[RF built-in variables]http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#built-in-variables)

**Comment by romuluc** [comment]
@RaiMan @rainmanwy The ${EMPTY} variable works!
