### ISSUE TITLE
SikuliLibrary vs SikuliX IDE

### ISSUE THREAD

**Issue by mzbedat** [rainmanwy/robotframework-SikuliLibrary#8]
Hi,
I'm trying to run sikuli on iOS device (connecting to it via VNC) but am facing issues with the image recognition!

If I try to click on Safari.png for example am getting match score = 0.88(Get Match Score Keyword)
But when I tried for other apps (Chrome, Netflix, ...) am getting the score as ZERO!!!

If I use SikuliX IDE to click on the same images it works fine.

I have most updated version:MacBook:~ 
$ pip install robotframework-sikulilibrary
Requirement already satisfied (use --upgrade to upgrade): robotframework-sikulilibrary in /Library/Python/2.7/site-packages

**Comment by rainmanwy** [comment]
Hi,

Could you post script of sikuli IDE you are using?
And how about the version of sikuli IDE you are using?
And how do you capture  png files? So library and IDE are using same png files, and library only works for Safari.png?

I am not sure whether there are different conditions between IDE and library. Maybe you could check that and give more details.

**Comment by rainmanwy** [comment]
I am not sure whether you using vnc in IDE like below:
http://sikulix-2014.readthedocs.io/en/latest/screen.html#connecting-to-a-vnc-server-vncscreen

this is not included in library. I guess if you capture png from vnc client(just treat vnc client as local application),  should work.

**Comment by mzbedat** [comment]
Hi,
Actually I'm not connecting to vnc via the script, I'm doing it manually meanwhie (is there a code that can work with python/robotframework for the VNCScreen object?).

However,
What I did to solve the problem is to capture screenshots via IDE tool --> Save the script --> open its content and take the images from there.
(rather than using Snip tool on Mac)

It works better, sometimes the the match is less than 0.75 but in code I did something that check the similarity, then compare it with a threshold.

B.R.

**Comment by rainmanwy** [comment]
The link i provided has provide the method to start vnc session. but i haven't tried it.
`vnc = vncStart("192.168.2.25") # some VNC Server in the local net

# create from scratch
remoteRegion = vnc.newRegion(x, y, w, h)
remoteRegion = vnc.newRegion(someRegion)`

As the link described, vnc related operation is developed out of sikuli, it is packaged in "edu.unh.iol.dlc." And this is not included in my lib yet.

So you open vnc client manually, and capture screenshots through IDE. And these png files could not work in the library(the match score is zero)? Am i correct?

If so, maybe we need ask help from sikulix author, whether there are some default settings in IDE for python, but not in java.
https://answers.launchpad.net/sikuli

**Comment by mzbedat** [comment]
Nope :)
What I'm saying that when using the screenshots captured by IDE it works fine with the sikulylibrary as well.
Seems that the problem was with the Mac "Snip" tool for taking screenshots, a different algorithm of pixiling maybe!

**Comment by rainmanwy** [comment]
ok. 

So the png files which Mac "Snip" tool captured could work in  IDE, but not work in library?
Or the origin problem you mentioned is not correct?

**Comment by mzbedat** [comment]
The description I provided was incorrect (miss-leading):
"If I use SikuliX IDE to click on the same images it works fine."
I meant by "Same images", the same visual image and not the same physical image file.

We can ignore this issue and mark it as closed, since the library is working as expected.

I have one more question, not sure if I need to open a new thread or if it can be answered here.
I want to add more functionality to the sikulilibrary (such like Right\Left Swap), and I'm trying to use python for that purpose:

`
from sikuli import *
from org.sikuli.script import *
import org.sikuli.script.SikulixForJython

def swap_right(self):      
        # setting begin - end
        x1, y1, x2, y2 = (640, 512, 640, 412)
        start = Location(x1, y1)
        end = Location(x2, y2)

        # moving left
        stepX = 10
        stepY = 0
        run = start
        mouseMove(start); wait(0.5)
        mouseDown(Button.LEFT); wait(0.5)
        for i in range(20):
                run = run.right(stepX).above(stepY)
                mouseMove(run)
                wait(0.1)
        mouseUp()`

But the interpreter is not recognizing the sikuli jar classes (such as Location).
How can I use the sikuli jar classes from inside python?

**Comment by rainmanwy** [comment]
sikuli is implemented with java, And can work in jython, not python.

for this library, i implement keywords with java basded on doc 
http://nightly.sikuli.de/docs/index.html

And keywords are in 
https://github.com/rainmanwy/robotframework-SikuliLibrary/tree/master/src/java/com/github/rainmanwy/robotframework/sikulilib/keywords
If you want, you could add keywords, and send pull request to me.

and if you want to implement keywords with python, you may check sikulix's doc, i remember it is mentioned.
