### ISSUE TITLE
Mouse Down\Up Keywords

### ISSUE THREAD

**Issue by mzbedat** [rainmanwy/robotframework-SikuliLibrary#9]
Hi,
According to documentation the Mouse Down & Mouse Up are getting mouseButtons argument, but in dead am getting that it's expecting 0 arguments!

In "robotframework-SikuliLibrary/src/java/com/github/rainmanwy/robotframework/sikulilib/keywords/ScreenKeywords.java" I can see that the implementation support the argument... but from robot its not.

I tried to uninstall it and reinstall with: python setup.py install but I got an error:

> The directory '/Users/galil/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling robotframework-SikuliLibrary-0.1.5:
  /Library/Python/2.7/site-packages/SikuliLibrary/__init__.py
  /Library/Python/2.7/site-packages/SikuliLibrary/__init__.pyc
  /Library/Python/2.7/site-packages/SikuliLibrary/lib/SikuliLibrary.jar
  /Library/Python/2.7/site-packages/SikuliLibrary/sikuli.py
  /Library/Python/2.7/site-packages/SikuliLibrary/sikuli.pyc
  /Library/Python/2.7/site-packages/SikuliLibrary/version.py
  /Library/Python/2.7/site-packages/SikuliLibrary/version.pyc
  /Library/Python/2.7/site-packages/robotframework_SikuliLibrary-0.1.5-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled robotframework-SikuliLibrary-0.1.5
The directory '/Users/galil/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
MacBook:LaunchDaemons galil$ cd ~
MacBook:~ galil$ cd git/robotframework-SikuliLibrary/
MacBook:robotframework-SikuliLibrary galil$ pip setup.py install
ERROR: unknown command "setup.py"
MacBook:robotframework-SikuliLibrary galil$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    with open(join(dirname(abspath(__file__)), 'target', 'src', 'SikuliLibrary', 'version.py')) as f:
IOError: [Errno 2] No such file or directory: '/Users/galil/git/robotframework-SikuliLibrary/target/src/SikuliLibrary/version.py'
MacBook:robotframework-SikuliLibrary galil$ 

B.R.

**Comment by rainmanwy** [comment]
If you install it from source. Need install maven firstly. Then execute below command.
`
mvn package
python setup.py install
`

**Comment by mzbedat** [comment]
I did the installation with maven:

> MacBook:robotframework-SikuliLibrary galil$ sudo python setup.py install
Password:
running install
running build
running build_py
running install_lib
creating /Library/Python/2.7/site-packages/SikuliLibrary
copying build/lib/SikuliLibrary/__init__.py -> /Library/Python/2.7/site-packages/SikuliLibrary
creating /Library/Python/2.7/site-packages/SikuliLibrary/lib
copying build/lib/SikuliLibrary/lib/SikuliLibrary.jar -> /Library/Python/2.7/site-packages/SikuliLibrary/lib
copying build/lib/SikuliLibrary/sikuli.py -> /Library/Python/2.7/site-packages/SikuliLibrary
copying build/lib/SikuliLibrary/version.py -> /Library/Python/2.7/site-packages/SikuliLibrary
byte-compiling /Library/Python/2.7/site-packages/SikuliLibrary/__init__.py to __init__.pyc
byte-compiling /Library/Python/2.7/site-packages/SikuliLibrary/sikuli.py to sikuli.pyc
byte-compiling /Library/Python/2.7/site-packages/SikuliLibrary/version.py to version.pyc
running install_egg_info
Removing /Library/Python/2.7/site-packages/robotframework_SikuliLibrary-DEV-py2.7.egg-info
Writing /Library/Python/2.7/site-packages/robotframework_SikuliLibrary-DEV-py2.7.egg-info

But still getting:
Keyword 'SikuliLibrary.Mouse Down' expected 0 non-keyword arguments, got 1.

**Comment by mzbedat** [comment]
Meanwhile as a work around I used the "Drag and Drop" keyword (source and target are the same) to simulate holding mouse on icon... 
But please advise regarding the installation, why it didn't take affect? I'll need it further after making changes on your java classes for adding more functionality.

**Comment by rainmanwy** [comment]
Could you provide the detail how do you use this keyword?

And how about robotframework version you use?

**Comment by mzbedat** [comment]
HI,
My version is:

> $ pip show robotframework
---
Metadata-Version: 1.1
Name: robotframework
Version: 3.0
Summary: A generic test automation framework
Home-page: http://robotframework.org
Author: Robot Framework Developers
Author-email: robotframework@gmail.com
License: Apache License 2.0
Location: /Library/Python/2.7/site-packages
Requires: 
Classifiers:
  Development Status :: 5 - Production/Stable
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Programming Language :: Python :: 2
  Programming Language :: Python :: 3
  Topic :: Software Development :: Testing

About how do I use it, it's straight forward... simply using the keyword from a test case!
I have a keyword.txt file that includes test cases and keywords, e.g.

`*** Test Cases ***
MyTest  
  ...
   Mouse Down  LEFT
  ...
  Mouse Up        LEFT
`

**Comment by rainmanwy** [comment]
So, "drag and drop" could work in your environment. But when use "mouse" related keywords, may met 

Keyword 'SikuliLibrary.Mouse Down' expected 0 non-keyword arguments, got 1.

**Comment by mzbedat** [comment]
Yes, drag and drop is working
Mouse Down\Up without any parameter is passing compilation but not performing the job
Mouse Down\Up with parameter (LEFT\RIGHT\...) is not working at all

**Comment by mzbedat** [comment]
Correction... only combination of both works:

`\	## Option 1
	\	SikuliLibrary.Mouse Move	netflix_taskbar.png	
	\	SikuliLibrary.Mouse Down	#LEFT
	\	Builtin.Sleep				5s
	\	SikuliLibrary.Mouse Up		#LEFT
	\	## Option 2
	\	Builtin.Sleep				2s
	\	SikuliLibrary.Drag And Drop	netflix_taskbar.png		netflix_taskbar.png	
	\	Wait Until Screen Contain	netflix_close_app.png	10
	\	Click						netflix_close_app.png`

**Comment by rainmanwy** [comment]
You could fetch the latest version from github, and have a try again.
I have fixed this problem.

Thank you very much!
