### ISSUE TITLE
sikuliapi 1.1.4 issue: java.lang.exceptionInItializer:null

### ISSUE THREAD

**Issue by Andy-V-iolo** [rainmanwy/robotframework-SikuliLibrary#91]
Hi Rainmanwy,

I am migrating my automation from using python 2.7/ sikuli 1.1.2 -> python 3.x / sikuli 1.1.4.

I keep getting a java.lang.exceptionInItializer:null error when attempting to run my first test case:

Are there any prerequisites or config i need to do with the latest robotframework-SikuliLibrary on Windows 10?

I have place the sikuliapi.jar in my ext folder in java jre8 folder.

Cheers,

Andy

**Comment by RaiMan** [comment]
Any more info?
Any stack trace?

**Comment by rainmanwy** [comment]
hi, Andy

Do you install this library from pypi?

sikulixapi do not need to install As it is included in  SikuliLibrary.jar.

I have seen such kind of error before. As Raiman's suggestion, could you attach the log here, this library will generate log in current work directory.

And could you remove the sikuli directory from your home directory.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Andy-V-iolo** [comment]
Copy that. I will rebuild my image with just pypi library.

There were a lot of remnants on the machine. I will also provide a stack trace in the future.

Thanks again for all the hard work gentleman. This makes poorly designed UI very easy to automate.

**Comment by Andy-V-iolo** [comment]
Ok, everything is now working correctly. I removed the sikuliapi.jar and everything appears to be working now.

Thanks guys
