### ISSUE TITLE
Checking that jrobotremoteserver runs fails in Python 3.6

### ISSUE THREAD

**Issue by jpeltonen** [rainmanwy/robotframework-SikuliLibrary#93]
https://github.com/rainmanwy/robotframework-SikuliLibrary/blob/3728c6d07fb5d2b06d3f08cddeda1b650fd2db6e/src/python/sikuli.py#L177

Throws exception:

>  urllib.error.HTTPError: HTTP Error 403: Forbidden

With Python 2.7 works fine.

**Comment by jpeltonen** [comment]
Works ok in Windows 10 but not in Windows Server 2016.

**Comment by rainmanwy** [comment]
@jpeltonen, could you have a try below steps:
1. start Sikuli java process manually, [doc](https://github.com/rainmanwy/robotframework-SikuliLibrary#start-server-manually)
2. open browser, and access "http://127.0.0.1:<port>"

I am not sure whether it is related with windows firewall or something.
Firstly should confirm that sikuli could work in your Windows Server 2016.

**Comment by jpeltonen** [comment]
Here are the steps.

![image](https://user-images.githubusercontent.com/22810621/54587603-41d36b80-4a29-11e9-9a83-1a71ab82c79e.png)

![image](https://user-images.githubusercontent.com/22810621/54587632-557ed200-4a29-11e9-921f-70df1c8a46bb.png)

![image](https://user-images.githubusercontent.com/22810621/54587743-af7f9780-4a29-11e9-83a3-1b1f35c6bc27.png)

**Comment by rainmanwy** [comment]
@jpeltonen , when urllib report error, how about the output from SikuliLibrary java process. Could you confirm that python could access other website?

**Comment by jpeltonen** [comment]
Can access Google.com. Can't see anything appearing in command prompt running SikuliLibrary java process when error code 403 appears.

![image](https://user-images.githubusercontent.com/22810621/54603682-9f79af00-4a4d-11e9-8705-cd038e42a873.png)

**Comment by rainmanwy** [comment]
@jpeltonen , whether there is proxy in your environment?
So the jvm part should be ok as browser works here.

**Comment by jpeltonen** [comment]
yes there is a proxy setting.

**Comment by jpeltonen** [comment]
127.0.0.1 had to be added to proxy exception list:
![image](https://user-images.githubusercontent.com/22810621/54750969-1b0c6500-4be2-11e9-9c24-f452fffeed15.png)
