### ISSUE TITLE
about keyword 'wait until screen contain'

### ISSUE THREAD

**Issue by kishinnofate** [rainmanwy/robotframework-SikuliLibrary#94]
Hello,

I have done a lot of automated testing along with Sikulilibrary for a year so I must say thank you for creating this amazing library. Thank you so much :)

But now I have some problem after I upgrade my Java version. I can not run the test case which using Sikulilibrary but after I try ...

Library            SikuliLibrary     mode=NEW
Suite Setup        Start Sikuli Process
Suite Teardown     Stop Remote Server  

It seems work :) but I find problem with the keyword 'wait until screen contain' my cmd informs that with "Keyword 'Wait Until Screen Contain' failed after retrying for 10 seconds. The last error was: This library does not support keyword arguments."

While other keywords are working well, I don't know what I am doing wrong :'(
It would be the great help for me if you can give me some advises.

Thank you in advance,
Kishin

**Comment by rainmanwy** [comment]
@kishinnofate , thank you!

How about the java version in your environment, are you using Windows or other operating systems.
Could you attach the log files(sikuli java process) and robot log here, it could help me to check the reason.

**Comment by kishinnofate** [comment]
@rainmanwy , thank you for your support!

I am using Windows 10 and java 8 update 201 (build 1.8.0_201-b09) which I think it may be the lasted version of java

This is the output that show about the problem.

`<kw name="Wait Until Screen Contain" library="SikuliLibrary">
<doc>Wait until screen contain Wait until image shown in screen</doc>
<arguments>
<arg>A4.jpg</arg>
<arg>timeout= 2</arg>
</arguments>
<msg level="FAIL" timestamp="20190327 10:01:08.322">This library does not support keyword arguments.</msg>
<status endtime="20190327 10:01:08.322" starttime="20190327 10:01:08.322" status="FAIL"/>
</kw>
<msg level="FAIL" timestamp="20190327 10:01:08.322">Keyword 'wait until screen contain' failed after retrying for 10 seconds. The last error was: This library does not support keyword arguments.</msg>
<status endtime="20190327 10:01:08.322" starttime="20190327 10:00:58.252" status="FAIL"/>`

This is sikuli log file which I receive after the test script end.

`0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Mapped path / to library com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.
0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server starting
0 [main] INFO org.eclipse.jetty.server.Server  - jetty-7.x.y-SNAPSHOT
15 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - started o.e.j.s.ServletContextHandler{/,null}
259 [main] INFO org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:49575
259 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server started on port 49575.`

And this is cmd when it fail.

![2019-03-27_10-13-59](https://user-images.githubusercontent.com/48539985/55047994-2a276300-5079-11e9-929f-f97c1c2eff03.jpg)


Now, I change to use "screen should contain" keyword instead and it works well :'D. But I hope my information will be useful for you.

Thanks a lot for your help :)

**Comment by jpeltonen** [comment]
There is a problem with latest Robot Framework version with remote interface to Java libraries. Try downgrading RF if you have installed latest version.

**Comment by rainmanwy** [comment]
@kishinnofate , you may remove "timeout=". From the error message, keyword argument is not supported.
Or you could downgrade RF version as @jpeltonen  suggested.

**Comment by kishinnofate** [comment]
Thank to both of you! I try to remove "timeout" but it said it require 2 arguments for this keyword. You are right I just upgrade lasted version of RF so I will try downgrading it.

Thank you so much for all help

**Comment by rainmanwy** [comment]
@kishinnofate ,  you may use this keyword as below:
```
Wait Until Screen Contain   A4.png   4
```
not 
```
Wait Until Screen Contain   A4.png   timeout=4
```
"timeout=4" is "keyword argument", but the error said it is not supported!

**Comment by kishinnofate** [comment]
Oh, sorry for my mistake and thank you @rainmanwy ! It finally works! XD
Thank you very much!
