### ISSUE TITLE
sikuli robotframework - take picture if test is not passed

### ISSUE THREAD

**Issue by glardz98** [rainmanwy/robotframework-SikuliLibrary#99]
hi,

i create a report with sikuli with this code below, i want to take a picture if test is not passed

my sikuli script:

runScript("""
robot
*** Settings ***
Library ./inline/LoginLibrary
*** Test Cases ***
Test1 clic1
""")
class LoginLibrary(object):
  def clic1(self):
    click(Pattern("1558427226922.png").exact())

**Comment by rainmanwy** [comment]
@glardz98 , i think this is not related with SikuliLibrary.

You could do it in "test teardown"
